image: atlassian/default-image:2

pipelines:
  default:
    - step:
        name: "Déploiement via SSH"
        script:
          - pipe: atlassian/ssh-run:0.8.0
            variables:
              SSH_USER: $SSH_USER
              SERVER: $SSH_HOST
              COMMAND: |
                #echo "Début du déploiement"
                #mkdir -p ~/projet-test
                #exit
                
                #- echo "Copie des fichiers vers le VPS"
                #- scp -r * $SSH_USER@$SSH_HOST:~/projet-test/
                "- echo "Fichiers copiés avec succès"
                
                #      - echo "Répertoire courant :"
                #      - pwd
                #      - echo "Contenu local à transférer :"
                #      - ls -la
                #      - echo "Transfert vers le serveur"
                #      - scp -v -r * $SSH_USER@$SSH_HOST:/home/<username>/projet-test/
                #      - echo "Fichiers transférés ?"
                
                # Se place dans le bon dossier
                cd ~/projet-test

                # 1) Récupérer la dernière version
                git fetch origin main
                git reset --hard origin/main