image: atlassian/default-image:2

pipelines:
  default:
    - step:
        name: "Déploiement via SSH"
        script:
          - pipe: atlassian/ssh-run:0.8.0
            variables:
              SSH_USER: $SSH_USER
              SERVER: $SSH_HOST
              COMMAND: |
                #!/usr/bin/env bash
                set -e
                
                # Se place dans le bon dossier
                cd ~/testbitbuckethostinger

                # 1) Récupérer la dernière version
                git fetch origin main
                git reset --hard origin/main