version: '3.8'

services:
  sveltekit:
    image: node:20
    container_name: sveltekit-app
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"